---
#
# users and groups
#
users_and_groups:
  - user_name: osmexport
    group_name: dev
app_user: "{{ users_and_groups[0] }}"

#
# osm_export_tool
#
project_home: "/home/{{ app_user.user_name }}/dev"
virtualenv_dir: "{{ project_home }}/hotosm"
repo_name: "osm-export-tool2"
requirements_file: "{{ project_home }}/{{ repo_name }}/requirements-dev.txt"


#
# postgres
#
db_name: hot_exports_dev
db_user: "{{ app_user.user_name }}_pg"
db_password: password
pg_admin_user: 'postgres'
pg_default_auth_method: 'trust'

pg_cfg_pg_hba_default:
  - { type: local, database: all, user: '{{ pg_admin_user }}', address: '', method: '{{ pg_default_auth_method }}', comment: '' }
  - { type: local, database: all, user: all, address: '',             method: '{{ pg_default_auth_method }}', comment: '"local" is for Unix domain socket connections only' }
  - { type: host,  database: all, user: all, address: '127.0.0.1/32', method: '{{ pg_default_auth_method }}', comment: 'IPv4 local connections:' }
  - { type: host,  database: all, user: all, address: '10.0.2.2/32', method: '{{ pg_default_auth_method }}', comment: 'IPv4 local connections:' }
  - { type: host,  database: all, user: all, address: '::1/128',      method: '{{ pg_default_auth_method }}', comment: 'IPv6 local connections:' }

pg_cfg_pg_hba_passwd_hosts: []
pg_cfg_pg_hba_trust_hosts: []
pg_cfg_pg_hba_custom: []

#
# thirdparty installs for OSM and Garmin interaction
#
thirdparty_dir: usr/local/src
thirdparty_zipfiles:
  - url: http://download.osmand.net/latest-night-build/OsmAndMapCreator-main.zip
    exdir: osmandmapcreator
  - url: http://www.mkgmap.org.uk/download/mkgmap-r3672.zip
    exdir: mkgmap
  - url: http://www.mkgmap.org.uk/download/splitter-r435.zip
    exdir: splitter
mkgmap_basename: "{{ thirdparty_zipfiles[1].url | basename | regex_replace('.zip', '') }}"
splitter_basename: "{{ thirdparty_zipfiles[2].url | basename | regex_replace('.zip', '') }}"

#
# rabbitmq, celery and flower
#
rabbitmq_user: "{{ app_user.user_name }}_rabbitmq"
rabbitmq_pass: "{{ db_password }}"
flower_user: "{{ app_user.user_name }}_flower"
celery_user: "{{ app_user.user_name }}_celery"