---
#
# users and groups
#
admin_email: admin@posm.com

#
# osm_export_tool
#
project_home: "/opt"
git_repo_url: https://github.com/AmericanRedCross/osm-export-tool2.git
git_repo_branch: "posm"
project_root: "{{ project_home }}/{{ git_repo_url | basename | splitext | first }}"
project_static_dir: "{{ project_root }}/static/"
requirements_file: "{{ project_root }}/requirements.txt"
django_settings_mod_path: "core.settings.site"
settings_dest: "{{ project_root }}/core/settings/site.py"
server_name: "localhost"

#
# postgres
#
db_name: exports
db_user: "hot"
db_password: "{{ DB_PASSWORD }}" # you must set an environment variable called DB_PASSWORD to populate this
pg_admin_user: 'postgres'

#
# thirdparty installs for OSM and Garmin interaction
# TODO: make this less convoluted
#
thirdparty_dir: /opt
thirdparty_zipfiles:
  - url: http://download.osmand.net/latest-night-build/OsmAndMapCreator-main.zip
    exdir: "{{ thirdparty_dir }}/osmandmapcreator"
  - url: http://www.mkgmap.org.uk/download/mkgmap-r3672.zip
    exdir: "{{ thirdparty_dir }}/mkgmap"
  - url: http://www.mkgmap.org.uk/download/splitter-r435.zip
    exdir: "{{ thirdparty_dir }}/splitter"
osmandmapcreator_dir: "{{ thirdparty_zipfiles[0].exdir }}"
mkgmap_dir: "{{ thirdparty_zipfiles[1].exdir }}/{{ thirdparty_zipfiles[1].url | basename | splitext | first }}"
splitter_dir: "{{ thirdparty_zipfiles[2].exdir }}/{{ thirdparty_zipfiles[2].url | basename | splitext | first }}"

#
# rabbitmq, celery and flower
#
rabbitmq_user: "site_rabbitmq"
rabbitmq_pass: "{{ db_password }}"

#
# export folders and settings.py
#
exports_dir: /opt/exports
exports_staging_dir: "{{ exports_dir }}/staging/"
exports_media_dir: "/downloads/" # so nginx can handback downloads
exports_download_dir: "{{ exports_dir }}/download/"
garmin_xml_dest: "{{ project_root }}/utils/conf/garmin_config.xml"

#
# overpass api
#
overpass_api_url: http://overpass-api.de/api/interpreter

#
# nodejs
#
node_version: 4
