---
#- name: add apt repository for rabbitmq
#  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=absent
#
#- name: add apt rabbitmq key
#  apt_key: url=https://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=absent

- name: install rabbitmq server
  apt:
     name: rabbitmq-server
     state: present
     update_cache: yes

- name: add rabbitmq user
  rabbitmq_user:
    user: "{{ rabbitmq_user }}"
    password: "{{ rabbitmq_pass }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

- name: run 'sudo rabbitmq-plugins enable rabbitmq_management' for flower
  shell: 'sudo rabbitmq-plugins enable rabbitmq_management'
  notify: restart rabbitmq-server