---
#- name: restart overpassapi
#  service: name=overpassapi state=restarted enabled=yes

- name: restart gunicorn
  service: name=osm-export-tool2 state=restarted enabled=yes

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

#- name: restart apache2
#  service: name=apache2 state=restarted enabled=yes